# Generated by Django 5.2.5 on 2025-08-16 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='user_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.usercourse'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user_course', 'module')},
        ),
    ]
