# Generated by Django 5.2.5 on 2025-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]