services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: grocademy_user
      POSTGRES_PASSWORD: grocademy_password
      POSTGRES_DB: grocademy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grocademy_user -d grocademy_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: secret-key-lokal-anda
      DEBUG: '1'
      DATABASE_URL: postgres://grocademy_user:grocademy_password@db:5432/grocademy_db
    restart: unless-stopped

volumes:
  postgres_data: