# fly.toml app configuration file generated for grocademy on 2025-08-17T13:24:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grocademy-floral-cloud-341'
primary_region = 'sin'
console_command = '/code/manage.py shell'

swap_size_mb = 512

[build]
  [build.args]
    SECRET_KEY_DUMMY = "a-dummy-secret-key-for-building-only"

[deploy]
  release_command = 'python manage.py migrate'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[processes]
  # Mengurangi jumlah worker menjadi 1 agar lebih hemat memori
  app = "gunicorn monolith.wsgi:application --bind 0.0.0.0:8000 --workers 1"